### PR TITLE
Update MonoMod.RuntimeDetour to 25.1

### PR DESCRIPTION
**Pull request by ManlyMarco**
Fixes .NET 3.5 support broken by merging #79

### CODE REVIEW

**Comment by ManlyMarco** [comment]
Build artifact if anyone wants to test this PR https://github.com/BepInEx/HarmonyX/actions/runs/7446155868/artifacts/1153680205

**Comment by ManlyMarco** [comment]
@nike4613 I guess I should wait for a stable release before merging?

**Comment by nike4613** [comment]
"Stable" doesn't really mean anything except "tested". I'm currently trying to get people using it so that I can see if any issues crop up that I haven't found. So if anything, I'd rather you merge and make a release ASAP.

**Comment by ManlyMarco** [comment]
Since it looks like there are no major issues I'll merge this.

**Pull request merged**
